import type { Metadata } from 'next';
import localFont from 'next/font/local';

import QueryProvider from '../providers/query-client-provider';
import { AuthProvider } from '@/contexts/auth-context';
import { ThemeProvider } from '../providers/theme-provider';
import { Toaster } from '@/components/ui/toaster';

import '@/styles/globals.css';
import { CampaignProvider } from '@/contexts/campaign-context';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'TRPG Assistant',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <QueryProvider>
      <AuthProvider>
        <CampaignProvider>
          <html lang="en" suppressHydrationWarning>
            <body
              className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
              <ThemeProvider attribute="class" defaultTheme="dark">
                {children}
                <Toaster />
              </ThemeProvider>
            </body>
          </html>
        </CampaignProvider>
      </AuthProvider>
    </QueryProvider>
  );
}
